// Date: 22/12/2015 7:14:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.TRIUMPH.AOS.Models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class EnderCombatArmor extends ModelBiped
{
  //fields
    ModelRenderer RArm1;
    ModelRenderer RArm2;
    ModelRenderer RArm3;
    ModelRenderer RArm4;
    ModelRenderer RArm5;
    ModelRenderer LArm1;
    ModelRenderer LArm2;
    ModelRenderer LArm3;
    ModelRenderer LArm4;
    ModelRenderer LArm5;
    ModelRenderer Chest1;
    ModelRenderer Chest2;
    ModelRenderer Chest3;
    ModelRenderer Chest4;
    ModelRenderer Chest5;
    ModelRenderer Chest6;
    ModelRenderer Chest7;
    ModelRenderer Chest8;
    ModelRenderer Head1;
    ModelRenderer Head2;
    ModelRenderer Head3;
    ModelRenderer Head4;
    ModelRenderer Head5;
    ModelRenderer Head6;
    ModelRenderer Head7;
    ModelRenderer Head8;
    ModelRenderer Head9;
    ModelRenderer Head10;
    ModelRenderer Head11;
    ModelRenderer LLeg1;
    ModelRenderer LLeg2;
    ModelRenderer RLeg1;
    ModelRenderer RLeg2;

  public EnderCombatArmor(Float expand)
  {
    super(expand,0,64,128);
    textureWidth = 64;
    textureHeight = 128;

      RArm1 = new ModelRenderer(this, 44, 0);
      RArm1.addBox(-3F, -2.5F, -2F, 3, 1, 4);
      RArm1.setRotationPoint(-5F, 2F, 0F);
      RArm1.setTextureSize(64, 128);
      RArm1.mirror = true;
      setRotation(RArm1, 0F, 0F, 0F);
      RArm2 = new ModelRenderer(this, 26, 34);
      RArm2.addBox(-0.5F, -2.2F, -1.5F, 1, 1, 3);
      RArm2.setRotationPoint(-5F, 2F, 0F);
      RArm2.setTextureSize(64, 128);
      RArm2.mirror = true;
      setRotation(RArm2, 0F, 0F, 0F);
      RArm3 = new ModelRenderer(this, 33, 0);
      RArm3.addBox(-3.5F, -2F, -2F, 1, 6, 4);
      RArm3.setRotationPoint(-5F, 2F, 0F);
      RArm3.setTextureSize(64, 128);
      RArm3.mirror = true;
      setRotation(RArm3, 0F, 0F, 0F);
      RArm4 = new ModelRenderer(this, 44, 6);
      RArm4.addBox(-3F, -2F, -2.5F, 3, 6, 1);
      RArm4.setRotationPoint(-5F, 2F, 0F);
      RArm4.setTextureSize(64, 128);
      RArm4.mirror = true;
      setRotation(RArm4, 0F, 0F, 0F);
      RArm5.mirror = true;
      RArm5 = new ModelRenderer(this, 44, 6);
      RArm5.addBox(-3F, -2F, 1.5F, 3, 6, 1);
      RArm5.setRotationPoint(-5F, 2F, 0F);
      RArm5.setTextureSize(64, 128);
      RArm5.mirror = true;
      setRotation(RArm5, 0F, 0F, 0F);
      RArm5.mirror = false;

      this.bipedRightArm.addChild(RArm1);
      this.bipedRightArm.addChild(RArm2);
      this.bipedRightArm.addChild(RArm3);
      this.bipedRightArm.addChild(RArm4);
      this.bipedRightArm.addChild(RArm5);


      LArm1 = new ModelRenderer(this, 26, 34);
      LArm1.addBox(-0.5F, -2.2F, -2F, 1, 1, 4);
      LArm1.setRotationPoint(5F, 2F, 0F);
      LArm1.setTextureSize(64, 128);
      LArm1.mirror = true;
      setRotation(LArm1, 0F, 0F, 0F);
      LArm2.mirror = true;
      LArm2 = new ModelRenderer(this, 44, 0);
      LArm2.addBox(0F, -2.5F, -2F, 3, 1, 4);
      LArm2.setRotationPoint(5F, 2F, 0F);
      LArm2.setTextureSize(64, 128);
      LArm2.mirror = true;
      setRotation(LArm2, 0F, 0F, 0F);
      LArm2.mirror = false;
      LArm3 = new ModelRenderer(this, 33, 0);
      LArm3.addBox(2.5F, -2F, -2F, 1, 6, 4);
      LArm3.setRotationPoint(5F, 2F, 0F);
      LArm3.setTextureSize(64, 128);
      LArm3.mirror = true;
      setRotation(LArm3, 0F, 0F, 0F);
      LArm4.mirror = true;
      LArm4 = new ModelRenderer(this, 44, 6);
      LArm4.addBox(0F, -2F, -2.5F, 3, 6, 1);
      LArm4.setRotationPoint(5F, 2F, 0F);
      LArm4.setTextureSize(64, 128);
      LArm4.mirror = true;
      setRotation(LArm4, 0F, 0F, 0F);
      LArm4.mirror = false;
      LArm5 = new ModelRenderer(this, 44, 6);
      LArm5.addBox(0F, -2F, 1.5F, 3, 6, 1);
      LArm5.setRotationPoint(5F, 2F, 0F);
      LArm5.setTextureSize(64, 128);
      LArm5.mirror = true;
      setRotation(LArm5, 0F, 0F, 0F);

      this.bipedLeftArm.addChild(LArm1);
      this.bipedLeftArm.addChild(LArm2);
      this.bipedLeftArm.addChild(LArm3);
      this.bipedLeftArm.addChild(LArm4);
      this.bipedLeftArm.addChild(LArm5);


      Chest1 = new ModelRenderer(this, 39, 34);
      Chest1.addBox(-3.5F, 6F, 1.5F, 7, 5, 1);
      Chest1.setRotationPoint(0F, 0F, 0F);
      Chest1.setTextureSize(64, 128);
      Chest1.mirror = true;
      setRotation(Chest1, 0F, 0F, 0F);
      Chest2 = new ModelRenderer(this, 58, 16);
      Chest2.addBox(-3F, 6.5F, -3F, 1, 4, 1);
      Chest2.setRotationPoint(0F, 0F, 0F);
      Chest2.setTextureSize(64, 128);
      Chest2.mirror = true;
      setRotation(Chest2, 0F, 0F, 0F);
      Chest3 = new ModelRenderer(this, 40, 42);
      Chest3.addBox(-3F, 1F, -3F, 6, 4, 1);
      Chest3.setRotationPoint(0F, 0F, 0F);
      Chest3.setTextureSize(64, 128);
      Chest3.mirror = true;
      setRotation(Chest3, 0F, 0F, 0F);
      Chest4 = new ModelRenderer(this, 39, 34);
      Chest4.addBox(-3.5F, 0.5F, -2.5F, 7, 5, 1);
      Chest4.setRotationPoint(0F, 0F, 0F);
      Chest4.setTextureSize(64, 128);
      Chest4.mirror = true;
      setRotation(Chest4, 0F, 0F, 0F);
      Chest5 = new ModelRenderer(this, 58, 16);
      Chest5.addBox(2F, 6.5F, -3F, 1, 4, 1);
      Chest5.setRotationPoint(0F, 0F, 0F);
      Chest5.setTextureSize(64, 128);
      Chest5.mirror = true;
      setRotation(Chest5, 0F, 0F, 0F);
      Chest6 = new ModelRenderer(this, 57, 23);
      Chest6.addBox(-1F, 6.5F, -3F, 2, 4, 1);
      Chest6.setRotationPoint(0F, 0F, 0F);
      Chest6.setTextureSize(64, 128);
      Chest6.mirror = true;
      setRotation(Chest6, 0F, 0F, 0F);
      Chest7 = new ModelRenderer(this, 39, 34);
      Chest7.addBox(-3.5F, 0.5F, 1.5F, 7, 5, 1);
      Chest7.setRotationPoint(0F, 0F, 0F);
      Chest7.setTextureSize(64, 128);
      Chest7.mirror = true;
      setRotation(Chest7, 0F, 0F, 0F);
      Chest8 = new ModelRenderer(this, 39, 34);
      Chest8.addBox(-3.5F, 6F, -2.5F, 7, 5, 1);
      Chest8.setRotationPoint(0F, 0F, 0F);
      Chest8.setTextureSize(64, 128);
      Chest8.mirror = true;
      setRotation(Chest8, 0F, 0F, 0F);

      this.bipedBody.addChild(Chest1);
      this.bipedBody.addChild(Chest2);
      this.bipedBody.addChild(Chest3);
      this.bipedBody.addChild(Chest4);
      this.bipedBody.addChild(Chest5);
      this.bipedBody.addChild(Chest6);
      this.bipedBody.addChild(Chest7);
      this.bipedBody.addChild(Chest8);


      Head1 = new ModelRenderer(this, 15, 65);
      Head1.addBox(-4.5F, -8.5F, -4.5F, 9, 1, 9);
      Head1.setRotationPoint(0F, 0F, 0F);
      Head1.setTextureSize(64, 128);
      Head1.mirror = true;
      setRotation(Head1, 0F, 0F, 0F);
      Head2 = new ModelRenderer(this, 0, 48);
      Head2.addBox(-5F, -8F, -3.5F, 1, 5, 7);
      Head2.setRotationPoint(0F, 0F, 0F);
      Head2.setTextureSize(64, 128);
      Head2.mirror = true;
      setRotation(Head2, 0F, 0F, 0F);
      Head3 = new ModelRenderer(this, 0, 48);
      Head3.addBox(4F, -8F, -3.5F, 1, 5, 7);
      Head3.setRotationPoint(0F, 0F, 0F);
      Head3.setTextureSize(64, 128);
      Head3.mirror = true;
      setRotation(Head3, 0F, 0F, 0F);
      Head4 = new ModelRenderer(this, 0, 69);
      Head4.addBox(-4.5F, -8F, -4.5F, 1, 6, 9);
      Head4.setRotationPoint(0F, 0F, 0F);
      Head4.setTextureSize(64, 128);
      Head4.mirror = true;
      setRotation(Head4, 0F, 0F, 0F);
      Head5 = new ModelRenderer(this, 0, 69);
      Head5.addBox(3.5F, -8F, -4.5F, 1, 6, 9);
      Head5.setRotationPoint(0F, 0F, 0F);
      Head5.setTextureSize(64, 128);
      Head5.mirror = true;
      setRotation(Head5, 0F, 0F, 0F);
      Head6 = new ModelRenderer(this, 18, 55);
      Head6.addBox(-4F, -9F, -4F, 8, 1, 8);
      Head6.setRotationPoint(0F, 0F, 0F);
      Head6.setTextureSize(64, 128);
      Head6.mirror = true;
      setRotation(Head6, 0F, 0F, 0F);
      Head7 = new ModelRenderer(this, 0, 61);
      Head7.addBox(-4F, -6F, -4.5F, 8, 3, 0);
      Head7.setRotationPoint(0F, 0F, 0F);
      Head7.setTextureSize(64, 128);
      Head7.mirror = true;
      setRotation(Head7, 0F, 0F, 0F);
      Head8 = new ModelRenderer(this, 0, 33);
      Head8.addBox(-4F, -6F, -5F, 1, 4, 1);
      Head8.setRotationPoint(0F, 0F, 0F);
      Head8.setTextureSize(64, 128);
      Head8.mirror = true;
      setRotation(Head8, 0F, 0F, 0F);
      Head9 = new ModelRenderer(this, 7, 33);
      Head9.addBox(-4F, -8F, -5F, 8, 2, 1);
      Head9.setRotationPoint(0F, 0F, 0F);
      Head9.setTextureSize(64, 128);
      Head9.mirror = true;
      setRotation(Head9, 0F, 0F, 0F);
      Head10 = new ModelRenderer(this, 0, 33);
      Head10.addBox(3F, -6F, -5F, 1, 4, 1);
      Head10.setRotationPoint(0F, 0F, 0F);
      Head10.setTextureSize(64, 128);
      Head10.mirror = true;
      setRotation(Head10, 0F, 0F, 0F);
      Head11 = new ModelRenderer(this, 0, 41);
      Head11.addBox(-4F, -8F, 4F, 8, 5, 1);
      Head11.setRotationPoint(0F, 0F, 0F);
      Head11.setTextureSize(64, 128);
      Head11.mirror = true;
      setRotation(Head11, 0F, 0F, 0F);

      this.bipedHead.addChild(Head1);
      this.bipedHead.addChild(Head2);
      this.bipedHead.addChild(Head3);
      this.bipedHead.addChild(Head4);
      this.bipedHead.addChild(Head5);
      this.bipedHead.addChild(Head6);
      this.bipedHead.addChild(Head7);
      this.bipedHead.addChild(Head8);
      this.bipedHead.addChild(Head9);
      this.bipedHead.addChild(Head10);
      this.bipedHead.addChild(Head11);


      LLeg1.mirror = true;
      LLeg1 = new ModelRenderer(this, 21, 42);
      LLeg1.addBox(-1.5F, 2F, -2.5F, 3, 3, 1);
      LLeg1.setRotationPoint(2F, 12F, 0F);
      LLeg1.setTextureSize(64, 128);
      LLeg1.mirror = true;
      setRotation(LLeg1, 0F, 0F, 0F);
      LLeg1.mirror = false;
      LLeg2.mirror = true;
      LLeg2 = new ModelRenderer(this, 30, 42);
      LLeg2.addBox(-1.5F, 6F, -2.5F, 3, 4, 1);
      LLeg2.setRotationPoint(2F, 12F, 0F);
      LLeg2.setTextureSize(64, 128);
      LLeg2.mirror = true;
      setRotation(LLeg2, 0F, 0F, 0F);
      LLeg2.mirror = false;

      this.bipedLeftLeg.addChild(LLeg1);
      this.bipedLeftLeg.addChild(LLeg2);


      RLeg1 = new ModelRenderer(this, 21, 42);
      RLeg1.addBox(-1.5F, 2F, -2.5F, 3, 3, 1);
      RLeg1.setRotationPoint(-2F, 12F, 0F);
      RLeg1.setTextureSize(64, 128);
      RLeg1.mirror = true;
      setRotation(RLeg1, 0F, 0F, 0F);
      RLeg2 = new ModelRenderer(this, 30, 42);
      RLeg2.addBox(-1.5F, 6F, -2.5F, 3, 4, 1);
      RLeg2.setRotationPoint(-2F, 12F, 0F);
      RLeg2.setTextureSize(64, 128);
      RLeg2.mirror = true;
      setRotation(RLeg2, 0F, 0F, 0F);

      this.bipedRightLeg.addChild(RLeg1);
      this.bipedRightLeg.addChild(RLeg2);
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
